#!/usr/bin/env bash
#
#   Automatic setup of dot-home on a host/account.
#   See USAGE below for details.
#
set -Eeuo pipefail
trap 'ec=$?; echo 1>&2 "INTERNAL ERROR: ec=$ec line=$LINENO cmd=$BASH_COMMAND";
      exit $ec;' ERR

dh_bootstrap_users_default=https://raw.githubusercontent.com/dot-home/dot-home/main/dh/bootstrap-users
DH_BOOTSTRAP_USERS=${DH_BOOTSTRAP_USERS:-$dh_bootstrap_users_default}
dh_repo=https://github.com/dot-home/dot-home
dh_local="$HOME/.home/dot-home"

####################################################################

USAGE="\
Usage: $(basename "$0")

This command bootstraps a dot-home configuration for the user specified in
\$LOGNAME. (POSIX XBD 8.3 specifies that this defaults to the current user.[1])

This reads the \$DH_BOOTSTRAP_USERS file (default [2]) which contains lines
of three whitespace-separated fields: login-name, repo-url and repo-name. It
will find the first line whose login-name matches \$LOGNAME and:
  1. Clone the repo specified in repo-url to \$HOME/.home/<repo-name>
  2. Clone the dot-home repo to \$HOME/.home/dot-home
  3. Run \$HOME/.home/dot-home/bin/dot-home-setup -u

This script is typically run using the following command:

    curl -sfL https://raw.githubusercontent.com/dot-home/dot-home/main/bootstrap-user | bash

See the dot-home README.md file[3] for more information.

[1]: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html
[2]: $dh_bootstrap_users_default
[3]: $dh_repo
"

####################################################################

die()  { local ec=$1; shift; echo 1>&2 "$@"; exit $ec; }

clone_or_update() {
    local url="$1" dir="$2"
    if [[ ! -d $dir ]]; then
        git clone -q "$url" "$dir"
    else
        git -C "$dir" fetch -q
        git -C "$dir" rebase -q
    fi

}

[[ "${#@}" -eq 0 ]] || { echo "$USAGE"; exit 2; }
echo "━━━━━ dot-home bootstrap for user $LOGNAME"

echo "Reading $DH_BOOTSTRAP_USERS"
while read logname user_repo_url user_local_repo; do
    [[ $logname == $LOGNAME ]] || continue
    [[ -n $user_local_repo ]] || user_local_repo=${user_repo_url##*/}
    break
done < <(curl -sfL "$DH_BOOTSTRAP_USERS")

if [[ $logname != $LOGNAME ]]; then
    echo "Warning: cannot find user $LOGNAME in $DH_BOOTSTRAP_USERS"
else
    echo "───── Cloning $user_local_repo from $user_repo_url"
    clone_or_update "$user_repo_url" "$HOME/.home/$user_local_repo"
fi

echo "───── Cloning dot-home from $dh_repo"
clone_or_update "$dh_repo" "$dh_local"

echo '───── Backing up to ~/OLD/'
#   XXX This does not check dependencies because they have not yet
#   been cloned, because dot-home has not yet been run. We probably
#   need a better way to do this, perhaps by asking dot-home to show
#   us what would conflict before it actually does the install.
old="$HOME/OLD"; mkdir -p "$old"
while read dotfile; do
    homefile="$HOME/.$dotfile"
    dirname=$(dirname "$dotfile")
    [[ -f $homefile ]] || continue
    #   -f on a working symlink is true. But we assume a symlink was
    #   installed by dot-home and don't back it up.
    [[ -L $homefile ]] && continue
    if [[ -f $old/$dotfile ]]; then
        echo "backup exists: $dotfile"
    else
        echo "   backing up: $dotfile"
        mkdir -p "$old/$dirname"
        mv "$HOME/.$dotfile" "$old/$dotfile"
    fi
done < <(cd "$HOME/.home" \
    && find */dot/ -type f \
        | grep -v '^[,_]inb4/' \
        | sed -e 's/\.inb.$//' -e 's,[^/]*/dot/,,' \
        | sort -u )

echo "───── Running dot-home-setup"
"$dh_local"/bin/dot-home-setup
echo "Test in a new window, or 'source ~/.bashrc'."
